model_name: BMCAN_Res2Next

cate_to_label_dict: {'bg':0, "la_myo": 1,  'la_blood':2, 'lv_blood':3, 'aa':4}
label_to_cate_dict: {'0':'bg', '1':'la_myo',  '2':'la_blood', '3':'lv_blood', '4':'aa'}
cal_class_list: [1,2,3,4]

# sample data csv
all_mmwh_cmda_ct_train_sample_csv_path: './csv/all_mmwh_cmda_ct_all_training_sample_data.csv'
all_mmwh_cmda_mr_train_sample_csv_path: './csv/all_mmwh_cmda_mr_training_sample_data.csv'

all_mmwh_cmda_ct_val_sample_csv_path: './csv/all_mmwh_cmda_ct_validation_sample_data.csv'
all_mmwh_cmda_mr_val_sample_csv_path: './csv/all_mmwh_cmda_mr_validation_sample_data.csv'

# real test csv
all_mmwh_cmda_real_test_ct_data_csv_path: './csv/all_mmwh_cmda_real_test_ct_data.csv'
all_mmwh_cmda_real_test_mr_data_csv_path: './csv/all_mmwh_cmda_real_test_mr_data.csv'


gpus: [8]
isTrain: True
image_size: [256, 256]
use_aug: True

num_workers: 0

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # Model Parameter
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

source:
    name: cardiac_ct
    range: [-2.8, 3.2]
target:
    name: cardiac_mri
    range: [-1.8, 4.4]


out_dir: ./result/
seed: 2021
size_H: 256
size_W: 256
size_C: 1
n_class: 5

skip: False
cudnn_enabled: True
cudnn_benchmark: True
cudnn_deterministic: False


# optimizer:
# name: 'Adam'
name: 'Adam'
lr_seg: 0.0002
lr_dp: 0.00005
lr_rec: 0.001
lr_dis: 0.0001
power: 0.9
weight_decay: 0.0005
momentum: 0.9
betas: [0.9, 0.99]
gan_betas: [0.5, 0.999]

# training, all samples: 2*1000*50 = 100000, all iterations: 1000*50 = 50k
train_batch_size: 2
val_batch_size: 2
iter_val: 250
max_epoch: 200



adv_p_smooth: 'softmax'

lambda_seg_sup_s: 1.0
lambda_aux: 0.1
lambda_s2t_seg: 1.0

# adv image
lambda_adv_i: 0.01
lambda_adv_p: 0.1
lambda_adv_tp: 0.1
lambda_rec: 1.0
lambda_ana_consis: 0.001

augmentations: None
start_s2t_seg: 0
lr_schedule: True
resume: 0
optimizer_resume: False #True
gan_resume: False


# nce weights
lambda_NCE: 0.5
nce_feature_dim_list: [64,256,512,1024,2048]
shared_code_channels: 2048
netF_nc: 256
nce_T: 0.07
init_gain: 0.02
num_patches: 256

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #



workdir: ./work_dir/BMCAN_Res2Next_CT2MR/
