model_name: BMCAN

cate_to_label_dict: {'bg':0, "la_myo": 1,  'la_blood':2, 'lv_blood':3, 'aa':4}
label_to_cate_dict: {'0':'bg', '1':'la_myo',  '2':'la_blood', '3':'lv_blood', '4':'aa'}
cal_class_list: [1,2,3,4]

# sample data csv
all_mmwh_cmda_ct_train_sample_csv_path: './csv/all_mmwh_cmda_ct_training_sample_data.csv'
all_mmwh_cmda_mr_train_sample_csv_path: './csv/all_mmwh_cmda_mr_training_sample_data.csv'

all_mmwh_cmda_ct_val_sample_csv_path: './csv/all_mmwh_cmda_ct_validation_sample_data.csv'
all_mmwh_cmda_mr_val_sample_csv_path: './csv/all_mmwh_cmda_mr_validation_sample_data.csv'

# real test csv
all_mmwh_cmda_real_test_ct_data_csv_path: './csv/all_mmwh_cmda_real_test_ct_data.csv'
all_mmwh_cmda_real_test_mr_data_csv_path: './csv/all_mmwh_cmda_real_test_mr_data.csv'


gpus: [4]
isTrain: True
image_size: [256, 256]
use_aug: True

num_workers: 0

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# # Model Parameter
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

source:
    name: cardiac_mri
    range: [-1.8, 4.4]
target:
    name: cardiac_ct
    range: [-2.8, 3.2]


out_dir: ./result/
seed: 2021
size_H: 256
size_W: 256
size_C: 1
n_class: 5

skip: False
cudnn_enabled: True
cudnn_benchmark: True
cudnn_deterministic: False

#model:
arch: 'ResNet50'
n_layers: 50
shared_code_channels: 2048
pretrained: False
n_bn: 1

# optimizer:
# name: 'Adam'
name: 'Adam'
lr_seg: 0.0002
lr_dp: 0.00005
lr_rec: 0.001
lr_dis: 0.0001
power: 0.9
weight_decay: 0.0005
momentum: 0.9
betas: [0.9, 0.99]
gan_betas: [0.5, 0.999]

# training, all samples: 2*1000*50 = 100000, all iterations: 1000*50 = 50k
train_batch_size: 3
val_batch_size: 3
iter_val: 250
max_epoch: 200

lambda_aux: 0.1
bnaffine: True
freeze_bn: False
adv_p_smooth: 'none'
lambda_s_seg: 1.0

lambda_adv_p: 0.1
lambda_adv_tp: 0.1
lambda_adv_i: 0.01
lambda_rec: 1.0
lambda_s2t_seg: 1.0
lambda_dice: 1.0

augmentations: None
start_s2t_seg: 0
lr_schedule: True
resume: 0
optimizer_resume: False #True
gan_resume: False


# nce weights
lambda_NCE: 0.5
nce_feature_dim_list: [64,64,256,512,2048]
netF_nc: 256
nce_T: 0.07
num_patches: 256

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #



workdir: ./work_dir/BMCAN_MR2CT/
