dataset_name: mmwh

# tfrecord dir
mmwh_cmda_tfrecord_data_dir: '../../data/Heart/MMWHS2017/PnpAda_release_data/train&val/'

# preprocess dir
mmwh_cmda_preprocess_npy_data_dir: '../../data/Heart/MMWHS2017_preprocess_npy/'

# sample dir
sample_ct_train_dir: '../../data/Heart/MMWHS2017_preprocess_npy/ct_train/'
sample_mr_train_dir: '../..//data/Heart/MMWHS2017_preprocess_npy/mr_train/'

sample_ct_val_dir: '../../data/Heart/MMWHS2017_preprocess_npy/ct_test/'
sample_mr_val_dir: '../..//data/Heart/MMWHS2017_preprocess_npy/mr_test/'

# real test data
mmwh_cmda_real_test_ct_data_dir: '../../data/Heart/MMWHS2017/test_ct_image&labels/'
mmwh_cmda_real_test_mr_data_dir: '../../data/Heart/MMWHS2017/test_mr_image&labels/'

# csv
csv_dir: './csv/'

# sample data csv
all_mmwh_cmda_ct_train_sample_csv_path: './csv/all_mmwh_cmda_ct_training_sample_data.csv'
all_mmwh_cmda_mr_train_sample_csv_path: './csv/all_mmwh_cmda_mr_training_sample_data.csv'

all_mmwh_cmda_ct_val_sample_csv_path: './csv/all_mmwh_cmda_ct_validation_sample_data.csv'
all_mmwh_cmda_mr_val_sample_csv_path: './csv/all_mmwh_cmda_mr_validation_sample_data.csv'

# real test csv
all_mmwh_cmda_real_test_ct_data_csv_path: './csv/all_mmwh_cmda_real_test_ct_data.csv'
all_mmwh_cmda_real_test_mr_data_csv_path: './csv/all_mmwh_cmda_real_test_mr_data.csv'


# cate name to label
# (1)500:Left ventricle blood (LVC), (2)600:right ventricle blood cavity
# (3)420:left atrium blood cavity (LAC), (4)550:right atrium blood cavity
# (5)205:the myocardium of the left ventricle, (MYO)
# (6)820: the ascending aorta (AA)
# (7)850: the pulmonary artery
# SIFA: LVC(1), LAC(3), MYO(5), AA(6)

# 0,1,2,3,4,5,6,7 -> 0,1,3,5,6 -> 0,1,2,3,4
cate_to_label_dict: {'bg':0, "la_myo": 1,  'la_blood':2, 'lv_blood':3, 'aa':4}
label_to_cate_dict: {'0':'bg', '1':'la_myo',  '2':'la_blood', '3':'lv_blood', '4':'aa'}



